# Generated by Django 5.2.5 on 2025-08-08 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_user_gpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_additional_hashes",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, user can authenticate with additional password hashes stored in PasswordHash table.",
                verbose_name="Allow additional password hashes",
            ),
        ),
        migrations.CreateModel(
            name="PasswordHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Hashed password string", max_length=128
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_hashes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Hash",
                "verbose_name_plural": "Password Hashes",
                "ordering": ["-created_at"],
            },
        ),
    ]
