# Generated by Django 5.2.5 on 2025-08-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_user_use_additional_hashes_passwordhash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_senior",
        ),
    ]
