# Generated by Django 5.2.5 on 2025-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_alter_user_graduation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
