# Generated by Django 5.2.5 on 2025-08-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0014_auto_20220709_1700"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testscore",
            options={"ordering": ["exam_type"]},
        ),
    ]
